#!/bin/bash
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

cmd=`(
	IFS=:
	aliases="$HOME/.bashrc"
# || stest -fqr -n "$cache" "$aliases"
	if stest -dqr -n "$cache" $PATH; then
		(
		stest -flx $PATH
			source $aliases
			alias | sed 's/alias \([[:alnum:]]\+\)=.*/\1/'
		) | (
		echo -e "\
chromium
nautilus
gedit
transmission-gtk
easytag
gimp
inkscape
blender
firefox
sass_watch
nitrogen
brackets
filezilla
atom"
		sort -u
		) | tee "$cache" | dmenu -h 30 -w 262 -l 9 -x 20 -y 5 -dim 0.3 -o 0.8 "$@" &
	else
		dmenu -h 30 -w 262 -l 9 -x 20 -y 5 -dim 0.3 -o 0.8 "$@" < "$cache" &
	fi
)`
echo -e "source ~/.bashrc \n $cmd" | bash -O expand_aliases &
