#!/bin/bash
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

cmd=`(
	IFS=:
	aliases="$HOME/.bashrc"
# || stest -fqr -n "$cache" "$aliases"
	if stest -dqr -n "$cache" $PATH; then
		(
		stest -flx $PATH
			source $aliases
			alias | sed 's/alias \([[:alnum:]]\+\)=.*/\1/'
		) | (
		echo -e "\
chromium
google-chrome-stable
nautilus
gedit
nitrogen
easytag
firefox
brackets
filezilla
transmission-gtk
gimp
inkscape
blender
atom"
		sort -u
		) | tee "$cache" | dmenu -h 30 -w 240 -l 9 -x 10 -y 10 "$@"
	else
		dmenu -h 30 -w 240 -l 9 -x 10 -y 10 "$@" < "$cache"
	fi
)`
echo -e "source ~/.bashrc \n $cmd" | bash -O expand_aliases &
