#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

. config

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

export PANEL_FIFO="/tmp/panel-fifo"
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $panel_height
#GTK_THEME=elementary slingshot-launcher --silent &
slingshot-launcher --silent &

bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
#conky > "$PANEL_FIFO" &
panel_mpd()
{
        mpc -f "%artist% - %album% - %title%" current
}
while true; do
	si="play.xbm"
	if [ "`mpc | grep "^\[playing\]"`" != "" ]; then
		si="pause.xbm"
	fi
	echo "M^ca(1, popup_music)^ca(2, mpc toggle)^i($icons/music.xbm)  $(panel_mpd)^ca()^ca()" > "$PANEL_FIFO"
        sleep 2s
done &
echo "T^i($icons/spkr_01.xbm)  "`ponymix get-volume | gdbar -bg $color_fg -fg $color_fg -w 100 -h 8 -s o -nonl` > "$PANEL_FIFO" &
#echo "T^i($icons/spkr_01.xbm)  "`amixer get Master | awk '$0~/%/{print $5}' | tr -d '[]%' | gdbar -bg $color_fg -fg $color_fg -w 100 -h 8 -s o -nonl` > "$PANEL_FIFO" &
clock -sf 'S%H:%M' > "$PANEL_FIFO" &

FONT_FAMILY='Terminus'
FONT_SIZE=11
cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -o 50 -h $panel_height -dock -ta l -title-name panel -fg "$color_fg" -bg "$color_bg" -e 'button2=;' &

wait
