#! /bin/sh

if [ $(pgrep -cx tint2) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

bspc config focus_follows_pointer false
bspc config bottom_padding $PANEL_HEIGHT
tint2
