#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

. config

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
#conky > "$PANEL_FIFO" &
panel_mpd()
{
        mpc -f "M^i($icons/note.xbm) %artist% - %album% - %title%" current
}
while true; do
	echo "$(panel_mpd)" > "$PANEL_FIFO"
        sleep 2s
done &
echo "T^i($icons/spkr_01.xbm) "`ponymix get-volume | gdbar -bg $color_fg -fg $color_se -w 83 -h 8 -s o -ss 1 -sw 3 -nonl` > "$PANEL_FIFO" &
clock -sf 'S%H:%M' > "$PANEL_FIFO" &

case "$flavor" in
	bar)
		cat "$PANEL_FIFO" | panel_bar | bar &
		;;
	dzen2)
		FONT_FAMILY='Terminus'
		FONT_SIZE=11
		cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "$font" -fg "$color_fg" -bg "$color_bg" -e 'button2=;' &
		;;
esac

wait
