#! /bin/sh

if [ $(pgrep -cx popup_music) -gt 1 ] ; then
	killall popup_music
fi

. config

mpt=$(mpc -f "%title% " current)
mpa=$(mpc -f "%album%" current)
mpb=$(mpc -f "%artist%" current)
art=$(mpc current -f %file% | sed 's_\(.*\)/\(.*\)/\(.*\)_\1/\2/_')

w=300
bw=$(expr $w - 75)

x=$((screen_width / 2 - w / 2 + 60))
ax=$((screen_width / 2 - w / 2 - 60))

position(){
	curr=$(mpc | awk 'NR==2' | awk '{print $3}' | sed 's/\/.*//')
	tot=$(mpc | awk 'NR==2' | awk '{print $3}' | sed 's/^.*\///')
	pos=$(mpc | awk 'NR==2' | awk '{print $4}' | sed 's/(//' | sed 's/%)//')
	bar=$(echo $pos | gdbar -w $bw -h 3 -fg "$color_se" -bg "$color_sf")
	echo -n " $curr $bar $tot"
	return
}

while :; do
echo " $mpt
 $mpa
 $mpb
^p(65)^ca(1, mpc prev)^i($icons/prev.xbm)^ca()   ^ca(1, mpc toggle)^i($icons/play.xbm)^ca()   ^ca(1, mpc stop)^i($icons/stop.xbm)^ca()   ^ca(1, mpc next)^i($icons/next.xbm)^ca()
$(position)"
sleep 1s 
done | dzen2 -p -x $x -l 4 -tw $w -w $w -h $panel_height -ta l -fn $font -bg $color_bg -fg $color_fg -e 'button1=exit;button2=exit;onstart=uncollapse;' &
bspc rule -a feh -o floating=on follow=on focus=off sticky=on borderless=yes && feh -Z -g 110x110+$ax+0 -^ art "/media/Data/Música/$art"
