#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

sleep 5s
bspc config top_padding 50
tint2 -c ~/.config/tint2/taskbarrc &
tint2 -c ~/.config/tint2/launcherrc &
tint2 -c ~/.config/tint2/trayrc &
pa-applet &
nm-applet &
plank &

wait
