#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

desktop_config() {
	bspc config $1 $2
	for M in $(bspc query -M); do
		bspc config -m $M $1 $2
	done
}

desktop_config border_width        1
bspc config normal_border_color "#000000"
bspc config focused_border_color "#000000"
bspc config presel_border_color "#4A90D9"
bspc config urgent_border_color "#4A90D9"
bspc config normal_sticky_border_color "#252e32"
bspc config focused_sticky_border_color "#252e32"
desktop_config window_gap          50
bspc config split_ratio         0.4
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^1
#bspc rule -a feh floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

panel &
sleep 3s && bspc rule -a urxvt -o pseudo_tiled=on desktop=^10 && urxvtc -e ncmpcpp &
